name: Eternal network PR workflow
on:
  pull_request:
    paths:
      - 'projects/eternal-network/**'

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        go-version: ['1.21.5']

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        working-directory: ./projects/eternal-network
        run: go get ./...
      - name: Test with Go
        working-directory: ./projects/eternal-network
        run: make test -- OPTS="-json" > results-test-${{ matrix.go-version }}
      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: Go-results-${{ matrix.go-version }}
          path: ./projects/eternal-network/results-test-${{ matrix.go-version }}